### ISSUE TITLE
how-to link on the hub landing page 404s

### ISSUE THREAD

**Issue by bsweger** [18F/hub#320]
Got an e-mail from a friendly contact this morning saying that the how-to link on the [hub landing page](https://18f.gsa.gov/hub/) 404s. Broken link is: https://18f.gsa.gov/hub/how-to/

**Comment by jeremiak** [comment]
Looks like the n00b link is broken as well: https://18f.gsa.gov/hub/n00b/

**Comment by afeld** [comment]
Lots of broken links, unfortunately :confused: Especially in the public version. Will fix as part of https://github.com/18F/hub/pull/297.

**Comment by mbland** [comment]
Heh, yeah... There's a bunch of "private" links on the front page that are broken on the "public" Hub. We've got an outstanding Doc Working Group task to migrate a bunch of content from "private" to "public", which will hopefully warrant this link and others valid rather than removing them.

@afeld @meiqimichelle @emileighoutlaw @gboone @elainekamlley @bsweger Perhaps we should brainstorm some candidates this week.

**Comment by wslack** [comment]
I don't think we can migrate a lot of that content - a lot of it relates to working internally at GSA and I don't think we can move the content to be public without a lot of checking first. I would also rather that people have the flexibility to edit the private content without worrying about clearing their edits for publication. Would we want to have a hub framework that enables the generic platform to have modular links from the homepage, and then modify the our own version of the hub to have the n00b pages?

cc @afeld @mbland

**Comment by mbland** [comment]
@wslack Came to that same conclusion quickly when putting together #321 and 18F/hub-pages-private#128. Went with the "modular" links, which point to the public or private n00b and how-to pages as necessary.

**Comment by wslack** [comment]
@mbland just had a sec to look and agreed with what you did. Thank you for jumping on this!
