### ISSUE TITLE
search broken on internal Hub

### ISSUE THREAD

**Issue by afeld** [18F/hub#546]
Works fine on https://18f.gsa.gov/hub/.

![screen shot 2016-02-09 at 10 54 26 pm](https://cloud.githubusercontent.com/assets/86842/12938321/2f349f16-cf80-11e5-9d92-879a69d864eb.png)

/cc @mbland

**Comment by mbland** [comment]
After comparing git checksums, and search file md5 sums, I tried to download the live index. Of course I found:

![broken-results](https://cloud.githubusercontent.com/assets/301547/12942638/9e9c7c32-cfaa-11e5-8f45-d28255ac55a4.png)

When I added the experimental `/search` endpoint for [18F/lunr-server](https://github.com/18F/lunr-server.js), its Nginx `location` directive intercepted `/search-index.json`. Just added a dedicated `location` rule for `/search-index.json` explicitly and we're back in business.

I did notice that the https://hub.18f.gov/hub/ build was breaking due to line 104 in `./go` getting an empty argument for `args`; I'll send a PR for that now.
