### ISSUE TITLE
Deploy Team Browser

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#568]
We want to move team browser to its own URL: team.18F.gov. 

We should discuss with @afeld to see if we can get some guidance

Acceptance Criteria:
I am an 18F employee
I navigate to team.18F.gov
I see the index page of the team browser

Per discussion today, start with pages. This might require a different authentication

**Comment by mtorres253** [comment]
Per discussion today aith @afeld, start with publishing as a pages site

**Comment by mtorres253** [comment]
https://pages.18f.gov/team-browser/

**Comment by mtorres253** [comment]
Hi @catherinedevlin, any progress on the private data? If not should I assign to someone else?

**Comment by catherinedevlin** [comment]
No progress - I've been 100% absorbed in other projects.  But let me see if I can implement Aidan's suggestion to deploy from Travis to get the private data secret safely over tonight/tomorrow morning.

**Comment by catherinedevlin** [comment]
So, aidan's suggestion on this was to deploy directly from Travis, which would carry the already-encrypted environment variables from Travis and take care of the question of how to get an HMAC_KEY environment variable set on the pages.18f.gov server.
https://18f.slack.com/archives/hub/p1458599027000516

However, what I didn't realize is that this implies deploying a whole freestanding jekyll server to cf as its own app, rather than piggybacking off the existing pages.18f.gov server.  That's more than I have time to get into right now - in fact, even deciding whether it's worth it calls for some real discussion, I think.  So I'm going to unassign from myself so that others can carry it on.

**Comment by mtorres253** [comment]
Let's move it to pages private for now so that we can surface private data

**Comment by mtorres253** [comment]
https://github.com/18F/Infrastructure/issues/597

**Comment by mtorres253** [comment]
This issue was moved to 18F/team-browser#78
